name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create dist directory
        run: mkdir dist
        shell: bash

      - name: Build binaries (Win/Mac/Linux)
        run: npm run build

      - name: Build Windows MSI Installer
        run: npm run build:msi

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/Easy-File-Size-Installer.msi
            dist/yoryo-win-x64.exe
            dist/yoryo-macos-x64
            dist/yoryo-linux-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
